export const ACCOUNT_CREATION_SUCCESS='ACCOUNT_CREATION_SUCCESS';
export const ACCOUNT_CREATION_ERROR='ACCOUNT_CREATION_ERROR';
export const ACCOUNT_CREATION_COMPLETED='ACCOUNT_CREATION_COMPLETED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_ERROR='LOGIN_ERROR';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';