export const IMGCATE_UPDATE_ANSWER='IMGCATE_UPDATE_ANSWER';
export const IMGCATE_OPEN_LIGHTBOX='IMGCATE_OPEN_LIGHTBOX';
export const IMGCATE_CLOSE_LIGHTBOX='IMGCATE_CLOSE_LIGHTBOX';
export const IMGCATE_SUBMIT_ERROR='IMGCATE_SUBMIT_ERROR';
export const IMGCATE_SUBMIT_SUCCESS='IMGCATE_SUBMIT_SUCCESS';
export const IMGCATE_SUBMIT_COMPLETED='IMGCATE_SUBMIT_COMPLETED';